### ISSUE TITLE
Add the IGG API

### ISSUE THREAD

**Issue by joscha** [AKERKits/akermap#6]
In order to automatically pull in backer locations and display them on the map.

**Comment by joscha** [comment]
Doesn't seem as if the IGG 1.1 API allows extracting backer information (e.g. address data). Waiting for IGG to come back for clarification.

**Comment by Amakaruk** [comment]
We talked about this specifically - I believe its available once we launch. We seem to get more privileges after we are live - I pinged Alisa, so we should have an answer soon.

**Comment by joscha** [comment]
Cool!

**Comment by Amakaruk** [comment]
Can we add a check box to the menu for IGG purchases, and can we strip the address from the API data for each backer so the marker only designates a given city. We don't want to violate privacy, and it would be cool to see cities kind of all aggregate orders (kind of a competition) in one location with a marker steadily increasing in number, since its all in the same spot.

**Comment by joscha** [comment]
@Amakaruk Yes, makes sense! Haven't gotten to that, yet.
